---
#########
- name: This sets up an httpd webserver
  hosts: web-servers
  become: true
  become_method: sudo
  tasks:
  - name: Install apache packages
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    service:
      name: httpd
      state: started
  - name: Pull file from source
    git:
      repo: 'https://github.com/nidheeshh/website.git'
      dest: /var/www/html
